name: 'Build and Terraform Apply when Push the main branch'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'TSC Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: 'Install Node Modules'
        run: pnpm install

      - name: 'Build'
        run: pnpm tsc --build

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build/

  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    needs:
      - build

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.4'

      - name: 'Set Up AWS Actions'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

      - name: 'Download Artifact'
        uses: actions/download-artifact@v4
        with:
          name: build_artifact

      - name: 'ls'
        run: ls -Gla

      - name: 'Terraform init'
        run: terraform -chdir=./terraform/environment/prd/ init

      - name: 'Terraform Plan'
        run: terraform -chdir=./terraform/environment/prd/ plan

# FIXME:
#      - name: 'Terraform Apply'
#        run: terraform -chdir=./terraform/environment/prd/ apply -auto-approve