name: 'Build and Terraform Apply when Push the main branch'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.4'

      - name: 'Set Up AWS Actions'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

      - name: 'Terraform init'
        run: terraform -chdir=./terraform/environment/prd/ init

      - name: 'Terraform Plan'
        run: terraform -chdir=./terraform/environment/prd/ plan

      - name: 'Terraform Apply'
        run: terraform -chdir=./terraform/environment/prd/ apply -auto-approval