name: 'Build and Terraform Plan when Pull Request on the main branch'

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: 'Install Node Modules'
        run: |
          pnpm webhook install
          pnpm subscribe install
        

      - name: 'Build'
        run: |
          pnpm webhook build
          pnpm subscribe build

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build

  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    needs:
      - build

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set Up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.4'

      - name: 'Set Up AWS Actions'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

      - name: 'Download Artifact'
        uses: actions/download-artifact@v4
        with:
          name: build_artifact
          path: build

      - name: 'Terraform init'
        run: terraform -chdir=./terraform/environment/prd/ init

      - name: 'Terraform Plan'
        run: terraform -chdir=./terraform/environment/prd/ plan -var "slack_webhook_base_url=${{ secrets.SLACK_WEBHOOK_BASE_URL }}" -var "slack_channel_resource=${{ secrets.SLACK_CHANNEL_RESOURCE }}"
