name: 'Build and Terraform Plan when Pull Request on the main branch'

on:
  push: # FIXME: will delete if this workflow works
    branches:
      - name
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout'
        uses: actions/checkout@4
        with:
          fetch-depth: 0

      - name: 'Set Up AWS Actions'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

        # FIXME: will delete if this workflow works
      - name: 'Get Caller Identity'
        run: aws sts get-caller-identity
